### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by Kyle-Kyle** [jbarlow83/homebrew-ocrmypdf#3]
~~~
Last 15 lines from /Users/Kyle/Library/Logs/Homebrew/ocrmypdf/06.pip:
  Removing source in /private/tmp/pip-nvftf_px-build
Command "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-nvftf_px-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-44fqgctx-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/ocrmypdf/5.3.2/libexec/bin/../include/site/python3.6/Pillow" failed with error code 1 in /private/tmp/pip-nvftf_px-build/
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/local/Cellar/ocrmypdf/5.3.2/libexec/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-nvftf_px-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-44fqgctx-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/ocrmypdf/5.3.2/libexec/bin/../include/site/python3.6/Pillow" failed with error code 1 in /private/tmp/pip-nvftf_px-build/
~~~

**Comment by jbarlow83** [comment]
Probably fixed now...
